
name: Create release
on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 

jobs:   
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Create Release Notes
      run: |
        chmod +x ./scripts/rz.py
        ./scripts/rz.py create ${{github.event.inputs.version}}
    - name: Commit and Push Changelog
      uses: EndBug/add-and-commit@v7.4.0
      with:
        default_author: github_actions
        message: 'Update changelog for v${{github.event.inputs.version}}' 
        add: 'CHANGELOG.md'
        tag: v${{github.event.inputs.version}}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
          tag: v${{github.event.inputs.version}}
          name: ReleaseZri v${{github.event.inputs.version}} released!
          bodyFile: ./.tmprz/release_notes.md
          draft: true
    - name: Clean Release Notes
      run: |
        ./scripts/rz.py cleanup
